### ISSUE TITLE
Certificate expired?

### ISSUE THREAD

**Issue by Potherca** [joinsolid/joinsolid.org#1]
When I tried to visit https://joinsolid.org/ (in Firefox) I got a "Potential Security Risk Ahead" warning.

According to the details the certificate has exprired:

>  Websites prove their identity via certificates, which are valid for a set time period. The certificate for joinsolid.org expired on 1/7/2019.

Screenshot: 
![image](https://user-images.githubusercontent.com/195757/84505491-1851d000-acbe-11ea-92fa-566fb76fbb7d.png)

**Comment by melvincarvalho** [comment]
@Potherca thanks for raising this.  I've no longer had time to maintain this site unfortunately, and it didnt really gain usage.  I'll renew the certificate if I get time, or possibly retire the site.  Thanks for the heads up, tho.

**Comment by Potherca** [comment]
Closing issue as `joinsolid.org` is no longer live.
